### ISSUE TITLE
uni-app版项目，为什么不是HBuilderX的项目

### ISSUE THREAD

**Issue by ygfgit** [dcloudio/test-framework#1]
这里的的uni-app版项目，为什么不是HBuilderX的项目？而是一个用vue-cli建起来的项目。难道HBuilderX建uni-app不如直接用vue-cli新建一个项目然后改造成uni-app好？

**Comment by hbcui1984** [comment]
这个是为了横向测试各框架，其它框架都是 cli 方式创建，故 uni-app 也使用了 cli 方式创建；

但从 uni-app 的维度来说，cli 方式更新比较频繁，适合喜欢尝鲜的开发者，HBuilderX 会定期发布正式版，适合追求稳定的开发者

**Comment by ygfgit** [comment]
明白了。看来开发还是HBuilderX 项目吧。谢谢！
